package service

import (
	"fmt"
	"strings"

	"github.com/phishingclub/phishingclub/errs"
	"github.com/phishingclub/phishingclub/model"
	"go.uber.org/zap"
)

// WebServerRulesGenerator generates ready-to-use redirect and filtering rules
// for Apache, Nginx, Caddy, and Traefik web servers.
type WebServerRulesGenerator struct {
	Common
	Logger *zap.SugaredLogger
}

// RulesConfig is the configuration for generating web server rules
type RulesConfig struct {
	// Target URL to redirect allowed visitors to
	TargetURL string `json:"targetURL"`
	// Decoy URL for blocked visitors
	DecoyURL string `json:"decoyURL"`
	// Server type: apache, nginx, caddy, traefik
	ServerType string `json:"serverType"`
	// Domain for the phishing site
	Domain string `json:"domain"`
	// Block known bot user agents
	BlockBots bool `json:"blockBots"`
	// Block known security scanner user agents
	BlockScanners bool `json:"blockScanners"`
	// Allowed countries (ISO 3166-1 alpha-2 codes)
	AllowedCountries []string `json:"allowedCountries,omitempty"`
	// Blocked IP ranges (CIDR notation)
	BlockedIPs []string `json:"blockedIPs,omitempty"`
	// Allowed IP ranges (CIDR notation)
	AllowedIPs []string `json:"allowedIPs,omitempty"`
	// Enable SSL/TLS enforcement
	ForceSSL bool `json:"forceSSL"`
	// Custom headers to inject
	CustomHeaders map[string]string `json:"customHeaders,omitempty"`
	// Enable referrer-based filtering
	RequireReferrer bool   `json:"requireReferrer"`
	AllowedReferrer string `json:"allowedReferrer,omitempty"`
}

// GeneratedRules is the output of the rules generator
type GeneratedRules struct {
	ServerType   string `json:"serverType"`
	Rules        string `json:"rules"`
	Filename     string `json:"filename"`
	Instructions string `json:"instructions"`
}

var botPatterns = []string{
	"googlebot", "bingbot", "slurp", "duckduckbot", "baiduspider",
	"yandexbot", "sogou", "facebot", "semrushbot", "dotbot",
	"rogerbot", "ahrefsbot", "mj12bot", "blexbot",
	"curl", "wget", "python-requests", "httpie", "go-http-client",
	"scrapy", "phantomjs", "headlesschrome",
}

var scannerPatterns = []string{
	"nessus", "nikto", "openvas", "nmap", "masscan", "qualys",
	"acunetix", "burpsuite", "zap", "sqlmap", "dirbuster", "gobuster",
	"barracuda", "proofpoint", "mimecast", "fireeye", "sophos",
	"forcepoint", "ironport", "messagelabs", "symantec",
}

// Generate creates web server rules based on the configuration
func (g *WebServerRulesGenerator) Generate(
	session *model.Session,
	config *RulesConfig,
) (*GeneratedRules, error) {
	isAuthorized, err := IsAuthorized(session, "campaign.create")
	if err != nil {
		g.LogAuthError(err)
		return nil, errs.Wrap(err)
	}
	if !isAuthorized {
		return nil, errs.ErrAuthorizationFailed
	}

	switch strings.ToLower(config.ServerType) {
	case "apache":
		return g.generateApache(config), nil
	case "nginx":
		return g.generateNginx(config), nil
	case "caddy":
		return g.generateCaddy(config), nil
	case "traefik":
		return g.generateTraefik(config), nil
	default:
		return nil, fmt.Errorf("unsupported server type: %s (use: apache, nginx, caddy, traefik)", config.ServerType)
	}
}

// GetSupportedServers returns the list of supported web server types
func (g *WebServerRulesGenerator) GetSupportedServers() []map[string]string {
	return []map[string]string{
		{"id": "apache", "name": "Apache (.htaccess)", "description": "Apache mod_rewrite rules"},
		{"id": "nginx", "name": "Nginx", "description": "Nginx server/location block configuration"},
		{"id": "caddy", "name": "Caddy", "description": "Caddyfile reverse proxy and redirect rules"},
		{"id": "traefik", "name": "Traefik", "description": "Traefik dynamic configuration (YAML)"},
	}
}

// --- Apache ---

func (g *WebServerRulesGenerator) generateApache(c *RulesConfig) *GeneratedRules {
	var b strings.Builder
	b.WriteString("# Apache Redirect & Filtering Rules\n")
	b.WriteString("# Generated by Phishing Club\n")
	b.WriteString("# Place in .htaccess or within <VirtualHost> block\n\n")
	b.WriteString("RewriteEngine On\n\n")

	if c.ForceSSL {
		b.WriteString("# Force HTTPS\n")
		b.WriteString("RewriteCond %{HTTPS} off\n")
		b.WriteString("RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n")
	}

	if c.BlockBots {
		b.WriteString("# Block known bots\n")
		for _, bot := range botPatterns {
			b.WriteString(fmt.Sprintf("RewriteCond %%{HTTP_USER_AGENT} %s [NC,OR]\n", bot))
		}
		// Remove trailing OR from last line
		b.WriteString(fmt.Sprintf("RewriteRule ^ %s [L,R=302]\n\n", c.DecoyURL))
	}

	if c.BlockScanners {
		b.WriteString("# Block security scanners\n")
		for _, scanner := range scannerPatterns {
			b.WriteString(fmt.Sprintf("RewriteCond %%{HTTP_USER_AGENT} %s [NC,OR]\n", scanner))
		}
		b.WriteString(fmt.Sprintf("RewriteRule ^ %s [L,R=302]\n\n", c.DecoyURL))
	}

	if len(c.BlockedIPs) > 0 {
		b.WriteString("# Block specific IPs\n")
		for _, ip := range c.BlockedIPs {
			b.WriteString(fmt.Sprintf("Deny from %s\n", ip))
		}
		b.WriteString("\n")
	}

	if c.RequireReferrer && c.AllowedReferrer != "" {
		b.WriteString("# Require specific referrer\n")
		b.WriteString(fmt.Sprintf("RewriteCond %%{HTTP_REFERER} !%s [NC]\n", c.AllowedReferrer))
		b.WriteString(fmt.Sprintf("RewriteRule ^ %s [L,R=302]\n\n", c.DecoyURL))
	}

	if len(c.CustomHeaders) > 0 {
		b.WriteString("# Custom headers\n")
		for k, v := range c.CustomHeaders {
			b.WriteString(fmt.Sprintf("Header set %s \"%s\"\n", k, v))
		}
		b.WriteString("\n")
	}

	b.WriteString("# Redirect allowed visitors to target\n")
	b.WriteString(fmt.Sprintf("RewriteRule ^(.*)$ %s [L,R=302]\n", c.TargetURL))

	return &GeneratedRules{
		ServerType: "apache",
		Rules:      b.String(),
		Filename:   ".htaccess",
		Instructions: "Place this file in the web root directory of your redirector server. " +
			"Ensure mod_rewrite and mod_headers are enabled: a2enmod rewrite headers && systemctl restart apache2",
	}
}

// --- Nginx ---

func (g *WebServerRulesGenerator) generateNginx(c *RulesConfig) *GeneratedRules {
	var b strings.Builder
	b.WriteString("# Nginx Redirect & Filtering Rules\n")
	b.WriteString("# Generated by Phishing Club\n\n")

	b.WriteString(fmt.Sprintf("server {\n"))
	b.WriteString(fmt.Sprintf("    listen 443 ssl;\n"))
	b.WriteString(fmt.Sprintf("    server_name %s;\n\n", c.Domain))

	b.WriteString("    ssl_certificate /etc/letsencrypt/live/" + c.Domain + "/fullchain.pem;\n")
	b.WriteString("    ssl_certificate_key /etc/letsencrypt/live/" + c.Domain + "/privkey.pem;\n\n")

	if c.ForceSSL {
		b.WriteString("}\n\nserver {\n")
		b.WriteString("    listen 80;\n")
		b.WriteString(fmt.Sprintf("    server_name %s;\n", c.Domain))
		b.WriteString("    return 301 https://$host$request_uri;\n")
		b.WriteString("}\n\nserver {\n")
		b.WriteString("    listen 443 ssl;\n")
		b.WriteString(fmt.Sprintf("    server_name %s;\n\n", c.Domain))
	}

	if len(c.BlockedIPs) > 0 {
		b.WriteString("    # Block specific IPs\n")
		for _, ip := range c.BlockedIPs {
			b.WriteString(fmt.Sprintf("    deny %s;\n", ip))
		}
		b.WriteString("\n")
	}

	if len(c.AllowedIPs) > 0 {
		b.WriteString("    # Allow only specific IPs\n")
		for _, ip := range c.AllowedIPs {
			b.WriteString(fmt.Sprintf("    allow %s;\n", ip))
		}
		b.WriteString("    deny all;\n\n")
	}

	if c.BlockBots || c.BlockScanners {
		b.WriteString("    # Block bots and scanners\n")
		b.WriteString("    if ($http_user_agent ~* \"")
		patterns := []string{}
		if c.BlockBots {
			patterns = append(patterns, botPatterns...)
		}
		if c.BlockScanners {
			patterns = append(patterns, scannerPatterns...)
		}
		b.WriteString(strings.Join(patterns, "|"))
		b.WriteString("\") {\n")
		b.WriteString(fmt.Sprintf("        return 302 %s;\n", c.DecoyURL))
		b.WriteString("    }\n\n")
	}

	if c.RequireReferrer && c.AllowedReferrer != "" {
		b.WriteString("    # Require specific referrer\n")
		b.WriteString(fmt.Sprintf("    if ($http_referer !~* \"%s\") {\n", c.AllowedReferrer))
		b.WriteString(fmt.Sprintf("        return 302 %s;\n", c.DecoyURL))
		b.WriteString("    }\n\n")
	}

	if len(c.CustomHeaders) > 0 {
		b.WriteString("    # Custom headers\n")
		for k, v := range c.CustomHeaders {
			b.WriteString(fmt.Sprintf("    add_header %s \"%s\";\n", k, v))
		}
		b.WriteString("\n")
	}

	b.WriteString("    location / {\n")
	b.WriteString(fmt.Sprintf("        proxy_pass %s;\n", c.TargetURL))
	b.WriteString("        proxy_set_header Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("        proxy_ssl_server_name on;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return &GeneratedRules{
		ServerType: "nginx",
		Rules:      b.String(),
		Filename:   c.Domain + ".conf",
		Instructions: "Place this file in /etc/nginx/sites-available/ and create a symlink: " +
			"ln -s /etc/nginx/sites-available/" + c.Domain + ".conf /etc/nginx/sites-enabled/ && nginx -t && systemctl reload nginx",
	}
}

// --- Caddy ---

func (g *WebServerRulesGenerator) generateCaddy(c *RulesConfig) *GeneratedRules {
	var b strings.Builder
	b.WriteString("# Caddyfile Redirect & Filtering Rules\n")
	b.WriteString("# Generated by Phishing Club\n\n")

	b.WriteString(fmt.Sprintf("%s {\n", c.Domain))
	b.WriteString("    # Automatic HTTPS via Let's Encrypt\n\n")

	if c.BlockBots || c.BlockScanners {
		patterns := []string{}
		if c.BlockBots {
			patterns = append(patterns, botPatterns...)
		}
		if c.BlockScanners {
			patterns = append(patterns, scannerPatterns...)
		}
		b.WriteString("    # Block bots and scanners\n")
		b.WriteString("    @blocked_ua {\n")
		b.WriteString(fmt.Sprintf("        header_regexp User-Agent \"(?i)(%s)\"\n", strings.Join(patterns, "|")))
		b.WriteString("    }\n")
		b.WriteString(fmt.Sprintf("    redir @blocked_ua %s 302\n\n", c.DecoyURL))
	}

	if len(c.BlockedIPs) > 0 {
		b.WriteString("    # Block specific IPs\n")
		b.WriteString("    @blocked_ip {\n")
		b.WriteString(fmt.Sprintf("        remote_ip %s\n", strings.Join(c.BlockedIPs, " ")))
		b.WriteString("    }\n")
		b.WriteString(fmt.Sprintf("    redir @blocked_ip %s 302\n\n", c.DecoyURL))
	}

	if len(c.CustomHeaders) > 0 {
		b.WriteString("    # Custom response headers\n")
		b.WriteString("    header {\n")
		for k, v := range c.CustomHeaders {
			b.WriteString(fmt.Sprintf("        %s \"%s\"\n", k, v))
		}
		b.WriteString("    }\n\n")
	}

	b.WriteString("    # Reverse proxy to target\n")
	b.WriteString(fmt.Sprintf("    reverse_proxy %s {\n", c.TargetURL))
	b.WriteString("        header_up Host {upstream_hostport}\n")
	b.WriteString("        header_up X-Real-IP {remote_host}\n")
	b.WriteString("        header_up X-Forwarded-For {remote_host}\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return &GeneratedRules{
		ServerType:   "caddy",
		Rules:        b.String(),
		Filename:     "Caddyfile",
		Instructions: "Place this file at /etc/caddy/Caddyfile and reload: systemctl reload caddy",
	}
}

// --- Traefik ---

func (g *WebServerRulesGenerator) generateTraefik(c *RulesConfig) *GeneratedRules {
	var b strings.Builder
	b.WriteString("# Traefik Dynamic Configuration\n")
	b.WriteString("# Generated by Phishing Club\n\n")

	b.WriteString("http:\n")
	b.WriteString("  routers:\n")
	b.WriteString(fmt.Sprintf("    phishing-router:\n"))
	b.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", c.Domain))
	b.WriteString("      service: phishing-service\n")
	b.WriteString("      entryPoints:\n")
	b.WriteString("        - websecure\n")
	b.WriteString("      tls:\n")
	b.WriteString("        certResolver: letsencrypt\n")

	if c.BlockBots || c.BlockScanners {
		b.WriteString("      middlewares:\n")
		b.WriteString("        - bot-filter\n")
	}

	b.WriteString("\n  services:\n")
	b.WriteString("    phishing-service:\n")
	b.WriteString("      loadBalancer:\n")
	b.WriteString("        servers:\n")
	b.WriteString(fmt.Sprintf("          - url: \"%s\"\n", c.TargetURL))
	b.WriteString("        passHostHeader: true\n")

	if c.BlockBots || c.BlockScanners || len(c.BlockedIPs) > 0 {
		b.WriteString("\n  middlewares:\n")
		if c.BlockBots || c.BlockScanners {
			patterns := []string{}
			if c.BlockBots {
				patterns = append(patterns, botPatterns...)
			}
			if c.BlockScanners {
				patterns = append(patterns, scannerPatterns...)
			}
			b.WriteString("    bot-filter:\n")
			b.WriteString("      headers:\n")
			b.WriteString("        customRequestHeaders:\n")
			b.WriteString(fmt.Sprintf("          # Block UA patterns: %s\n", strings.Join(patterns[:3], ", ")))
			b.WriteString("          # Note: Traefik requires plugin for UA filtering\n")
			b.WriteString("          # Use traefik-plugin-blockpath or custom middleware\n")
		}
		if len(c.BlockedIPs) > 0 {
			b.WriteString("    ip-filter:\n")
			b.WriteString("      ipWhiteList:\n")
			b.WriteString("        sourceRange:\n")
			for _, ip := range c.AllowedIPs {
				b.WriteString(fmt.Sprintf("          - \"%s\"\n", ip))
			}
		}
	}

	return &GeneratedRules{
		ServerType:   "traefik",
		Rules:        b.String(),
		Filename:     "dynamic.yml",
		Instructions: "Place this file in Traefik's dynamic configuration directory (e.g., /etc/traefik/dynamic/) and ensure file provider is configured in traefik.yml",
	}
}
